// <auto-generated />
using System;
using AppKetraInfraData.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppKetra.InfraData.Migrations
{
    [DbContext(typeof(AppKetraContexto))]
    [Migration("20201223153655_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("AppKetra.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("NumFornece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumFornece");

                    b.ToTable("SA2");
                });

            modelBuilder.Entity("AppKetra.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("NumPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DtEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumFornece")
                        .HasColumnType("int");

                    b.Property<int>("NumProduto")
                        .HasColumnType("int");

                    b.Property<float>("ValTotal")
                        .HasColumnType("real");

                    b.Property<float>("ValUnit")
                        .HasColumnType("real");

                    b.HasKey("NumPedido");

                    b.ToTable("SC7");
                });

            modelBuilder.Entity("AppKetra.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("NumProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumProduto");

                    b.ToTable("SB1");
                });

            modelBuilder.Entity("AppKetra.Domain.Entities.Status", b =>
                {
                    b.Property<int>("Num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DtLiberac")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumAprov")
                        .HasColumnType("int");

                    b.Property<int>("Situac")
                        .HasColumnType("int");

                    b.HasKey("Num");

                    b.ToTable("SCR");
                });
#pragma warning restore 612, 618
        }
    }
}
